var XzalgoChain=(()=>{var _scriptName=globalThis.document?.currentScript?.src;return async function(moduleArg={}){var moduleRtn;var d=moduleArg,n="",p;try{n=(new URL(".",_scriptName)).href}catch{}p=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var q=console.error.bind(console),r,t=!1,u,v,w,x,y,z,A,B,C,D,E,F=!1;function G(){var a=H.buffer;x=new Int8Array(a);z=new Int16Array(a);y=new Uint8Array(a);new Uint16Array(a);A=new Int32Array(a);B=new Uint32Array(a);C=new Float32Array(a);D=new Float64Array(a);E=new BigInt64Array(a);new BigUint64Array(a)}
function I(a){d.onAbort?.(a);a="Aborted("+a+")";q(a);t=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");w?.(a);throw a;}var J;async function ba(a){if(!r)try{var b=await p(a);return new Uint8Array(b)}catch{}if(a==J&&r)a=new Uint8Array(r);else throw"both async and sync fetching of the wasm failed";return a}async function ca(a,b){try{var c=await ba(a);return await WebAssembly.instantiate(c,b)}catch(e){q(`failed to asynchronously prepare wasm: ${e}`),I(e)}}
async function da(a){var b=J;if(!r)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(e){q(`wasm streaming compile failed: ${e}`),q("falling back to ArrayBuffer instantiation")}return ca(b,a)}class K{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var L=a=>{for(;0<a.length;)a.shift()(d)},M=[],N=[],ea=()=>{var a=d.preRun.shift();N.push(a)},O=!0,P=0,Q={},R=a=>{if(!(a instanceof K||"unwind"==a))throw a;},S=a=>{u=a;O||0<P||(d.onExit?.(a),t=!0);throw new K(a);},fa=a=>{if(!t)try{a()}catch(b){R(b)}finally{if(!(O||0<P))try{u=a=u,S(a)}catch(b){R(b)}}},T=a=>{for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);127>=e?b++:2047>=e?b+=2:55296<=e&&57343>=e?(b+=4,++c):b+=3}return b},U=(a,b,c)=>{var e=y;if(!(0<c))return 0;var f=b;c=b+c-1;for(var h=0;h<a.length;++h){var g=
a.codePointAt(h);if(127>=g){if(b>=c)break;e[b++]=g}else if(2047>=g){if(b+1>=c)break;e[b++]=192|g>>6;e[b++]=128|g&63}else if(65535>=g){if(b+2>=c)break;e[b++]=224|g>>12;e[b++]=128|g>>6&63;e[b++]=128|g&63}else{if(b+3>=c)break;e[b++]=240|g>>18;e[b++]=128|g>>12&63;e[b++]=128|g>>6&63;e[b++]=128|g&63;h++}}e[b]=0;return b-f},V=globalThis.TextDecoder&&new TextDecoder,W=(a=0,b,c)=>{var e=y;var f=a;b=f+b;if(c)c=b;else{for(;e[f]&&!(f>=b);)++f;c=f}if(16<c-a&&e.buffer&&V)return V.decode(e.subarray(a,c));for(f=
"";a<c;)if(b=e[a++],b&128){var h=e[a++]&63;if(192==(b&224))f+=String.fromCharCode((b&31)<<6|h);else{var g=e[a++]&63;b=224==(b&240)?(b&15)<<12|h<<6|g:(b&7)<<18|h<<12|g<<6|e[a++]&63;65536>b?f+=String.fromCharCode(b):(b-=65536,f+=String.fromCharCode(55296|b>>10,56320|b&1023))}}else f+=String.fromCharCode(b);return f},ja=(a,b,c,e)=>{var f={string:k=>{var l=0;if(null!==k&&void 0!==k&&0!==k){l=T(k)+1;var Z=X(l);U(k,Z,l);l=Z}return l},array:k=>{var l=X(k.length);x.set(k,l);return l}};a=d["_"+a];var h=[],
g=0;if(e)for(var m=0;m<e.length;m++){var aa=f[c[m]];aa?(0===g&&(g=ha()),h[m]=aa(e[m])):h[m]=e[m]}c=a(...h);return c=function(k){0!==g&&ia(g);return"string"===b?k?W(k):"":"boolean"===b?!!k:k}(c)};d.noExitRuntime&&(O=d.noExitRuntime);d.printErr&&(q=d.printErr);d.wasmBinary&&(r=d.wasmBinary);if(d.preInit)for("function"==typeof d.preInit&&(d.preInit=[d.preInit]);0<d.preInit.length;)d.preInit.shift()();d.ccall=ja;
d.cwrap=(a,b,c,e)=>{var f=!c||c.every(h=>"number"===h||"boolean"===h);return"string"!==b&&f&&!e?d["_"+a]:(...h)=>ja(a,b,c,h,e)};d.setValue=function(a,b,c="i8"){c.endsWith("*")&&(c="*");switch(c){case "i1":x[a]=b;break;case "i8":x[a]=b;break;case "i16":z[a>>1]=b;break;case "i32":A[a>>2]=b;break;case "i64":E[a>>3]=BigInt(b);break;case "float":C[a>>2]=b;break;case "double":D[a>>3]=b;break;case "*":B[a>>2]=b;break;default:I(`invalid type for setValue: ${c}`)}};
d.getValue=function(a,b="i8"){b.endsWith("*")&&(b="*");switch(b){case "i1":return x[a];case "i8":return x[a];case "i16":return z[a>>1];case "i32":return A[a>>2];case "i64":return E[a>>3];case "float":return C[a>>2];case "double":return D[a>>3];case "*":return B[a>>2];default:I(`invalid type for getValue: ${b}`)}};d.UTF8ToString=(a,b,c)=>a?W(a,b,c):"";d.stringToUTF8=(a,b,c)=>U(a,b,c);d.lengthBytesUTF8=T;
var ka,ia,X,ha,H,la={c:()=>I(""),b:()=>{O=!1;P=0},d:(a,b)=>{Q[a]&&(clearTimeout(Q[a].id),delete Q[a]);if(!b)return 0;var c=setTimeout(()=>{delete Q[a];fa(()=>ka(a,performance.now()))},b);Q[a]={id:c,A:b};return 0},e:a=>{var b=y.length;a>>>=0;if(536870912<a)return!1;for(var c=1;4>=c;c*=2){var e=b*(1+.2/c);e=Math.min(e,a+100663296);a:{e=(Math.min(536870912,65536*Math.ceil(Math.max(a,e)/65536))-H.buffer.byteLength+65535)/65536|0;try{H.grow(e);G();var f=1;break a}catch(h){}f=void 0}if(f)return!0}return!1},
a:S},Y;
Y=await (async function(){function a(c){c=Y=c.exports;d._xzalgochain_wasm=c.h;d._xzalgochain_init_wasm=c.i;d._xzalgochain_update_wasm=c.j;d._xzalgochain_final_wasm=c.k;d._xzalgochain_ctx_reset_wasm=c.l;d._xzalgochain_ctx_wipe_wasm=c.m;d._xzalgochain_copy_wasm=c.n;d._xzalgochain_equals_wasm=c.o;d._xzalgochain_version_wasm=c.p;ka=c.q;d._malloc=c.r;d._free=c.s;ia=c.t;X=c.u;ha=c.v;H=c.f;G();return Y}var b={a:la};if(d.instantiateWasm)return new Promise(c=>{d.instantiateWasm(b,(e,f)=>{c(a(e,f))})});
J??=d.locateFile?d.locateFile("XzalgoChain.wasm",n):n+"XzalgoChain.wasm";return a((await da(b)).instance)}());
(function(){function a(){d.calledRun=!0;if(!t){F=!0;Y.g();v?.(d);d.onRuntimeInitialized?.();if(d.postRun)for("function"==typeof d.postRun&&(d.postRun=[d.postRun]);d.postRun.length;){var b=d.postRun.shift();M.push(b)}L(M)}}if(d.preRun)for("function"==typeof d.preRun&&(d.preRun=[d.preRun]);d.preRun.length;)ea();L(N);d.setStatus?(d.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>d.setStatus(""),1);a()},1)):a()})();F?moduleRtn=d:moduleRtn=new Promise((a,b)=>{v=a;w=b});
;return moduleRtn}})();if(typeof exports==="object"&&typeof module==="object"){module.exports=XzalgoChain;module.exports.default=XzalgoChain}else if(typeof define==="function"&&define["amd"])define([],()=>XzalgoChain);
